#! /usr/bin/env bash
#
# Git subtree command

# https://dev.to/ifenna__/adding-colors-to-bash-scripts-48g4

green="32"
blue="34"
bb="\e[1;${blue}m"
end="\e[0m"


# Suppresses error message should remotes already exist
git remote add -f react-hooks "https://github.com/iseykim/react-hooks" 2>/dev/null
git remote add -f gatsby-tutorial "https://github.com/AmberAbreu/codyportfolio-boilerplate" 2>/dev/null
git remote add -f firebase "https://github.com/margaritadanshina/todo_firebase" 2>/dev/null

# Git subtree pull

printf "${bb}React Hooks${end}\n"
git subtree pull --prefix react-hooks react-hooks main --squash 

printf "${bb}Gatsby Tutorial${end}\n"
git subtree pull --prefix gatsby-tutorial gatsby-tutorial main --squash

printf "${bb}Firebase${end}\n"
git subtree pull --prefix firebase firebase main --squash
